CREATE TABLE IF NOT EXISTS "Users" (
    userID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    passwordHash VARCHAR(255) NOT NULL,
    fullName VARCHAR(100),
    role VARCHAR(20) CHECK (role IN ('customer','admin')) DEFAULT 'customer',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Products (
    productID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    productName VARCHAR(55) NOT NULL,
    productSize VARCHAR(10),
    productColor VARCHAR(20),
    productPrice DECIMAL(10,2) NOT NULL,
    productDiscount DECIMAL(5,2) DEFAULT 0.00,
    productCategory VARCHAR(255),
    userID INT,
    CONSTRAINT fk_Users FOREIGN KEY (userID) REFERENCES Users(userID)
);

CREATE TABLE Stock (
    stockID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    productID INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity >= 0),
    lastUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_Stock_Product FOREIGN KEY (productID) REFERENCES Products(productID)
);

CREATE TABLE Orders (
    orderID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    userID INT NOT NULL,
    orderDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) CHECK (status IN ('pending','paid','shipped','completed','cancelled')) DEFAULT 'pending',
    totalAmount DECIMAL(10,2),
    CONSTRAINT fk_Orders_User FOREIGN KEY (userID) REFERENCES Users(userID)
);

CREATE TABLE OrderItems (
    orderItemID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    orderID INT NOT NULL,
    productID INT NOT NULL,
    quantity INT DEFAULT 1,
    price DECIMAL(10,2),
    discount DECIMAL(5,2),
    CONSTRAINT fk_OrderItems_Order FOREIGN KEY (orderID) REFERENCES Orders(orderID),
    CONSTRAINT fk_OrderItems_Product FOREIGN KEY (productID) REFERENCES Products(productID)
);

CREATE TABLE Cart (
    cartID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    userID INT NOT NULL,
    productID INT NOT NULL,
    quantity INT DEFAULT 1,
    addedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_Cart_User FOREIGN KEY (userID) REFERENCES Users(userID),
    CONSTRAINT fk_Cart_Product FOREIGN KEY (productID) REFERENCES Products(productID)
);

CREATE TABLE Wishlist (
    wishlistID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    userID INT NOT NULL,
    productID INT NOT NULL,
    addedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_Wishlist_User FOREIGN KEY (userID) REFERENCES Users(userID),
    CONSTRAINT fk_Wishlist_Product FOREIGN KEY (productID) REFERENCES Products(productID)
);

-- 2️⃣ Create trigger function to update updatedAt
CREATE OR REPLACE FUNCTION update_updatedAt_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW."updatedAt" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 3️⃣ Create trigger on Users table
CREATE TRIGGER update_users_updatedAt
BEFORE UPDATE ON "Users"
FOR EACH ROW
EXECUTE FUNCTION update_updatedAt_column();